In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

# Load THE MOVIE dataset
themovies_ratings = pd.read_csv("../data/THEMOVIE_ds/ratings.csv")
themovies_metadata = pd.read_csv("../data/THEMOVIE_ds/themovies_metadata.csv")

/tmp/ipykernel_34769/2004645240.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  themovies_metadata = pd.read_csv("../data/THEMOVIE_ds/themovies_metadata.csv")

In [13]:
print("shape of ratings dataset: ", themovies_ratings.shape)
print("shape of metadata dataset: ", themovies_metadata.shape)

shape of ratings dataset:  (26024289, 4)
shape of metadata dataset:  (45466, 24)

In [42]:
#Ids that are bad formatted 
bad_ids = themovies_metadata[~themovies_metadata['id'].apply(lambda x: str(x).isdigit())]

themovies_metadata = themovies_metadata[~themovies_metadata['id'].isin(bad_ids['id'])]
themovies_metadata['id'] = themovies_metadata['id'].astype(int)

In [56]:
# Avereage rating of each movie 

summary_ratings = themovies_ratings.groupby('movieId')['rating'].agg(
    avg_rating='mean', 
    num_ratings='count',
    std_rating='std'
).reset_index()
summary_ratings.shape

(45115, 4)

In [46]:

themovie_merged = themovies_metadata.merge(summary_ratings, left_on= 'id', right_on= 'movieId', how = 'left').drop('movieId', axis=1)
themovie_merged.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,avg_rating,num_ratings,std_rating
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,3.598930,374.0,0.990355
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,3.760163,123.0,1.022993
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,NaN,NaN,NaN
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,NaN,NaN,NaN
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,NaN,NaN,NaN

In [ ]:
#!!!
themovie_merged.isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   3
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      3
runtime                    260
spoken_languages             3
status                      84
tagline                  25051
title                        3
video                        3
vote_average                 3
vote_count                   3
avg_rating               37894
num_ratings              37894
std_rating               38449
dtype: int64